model:
  arch: musillm
  model_type: pretrain_vicuna
  audio_first: True
  prompt_template: '###Human: {} ###Assistant: '
  end_sym: "###"
  audio_interpolation: False
  cer: 0.3

  ckpt: 'musilingo.pth'


datasets:
  mtt:
    data_type: audios
    genre: classical
    top_k: 10
    tf_idf: True
    unit_type: unigram # or bigram
    pct_other_genres: 0
      

run:
  task: audio_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 1 # 3
  batch_size_train: 8
  batch_size_eval: 2
  num_workers: 0
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "./outputs"

  amp: True
  resume_ckpt_path: null

  evaluate: True
  train_splits: ["train"]
  valid_splits: ["valid"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
